In [1]:
print("Hello I'm excited to learn pytorch")

Hello I'm excited to learn pytorch


In [2]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.4.1


In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to Tensor

### Creating tensor

Pytorch tensor can be created using "torch.Tensor()" = https://pytorch.org/docs/stable/tensors.html

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX
MATRIX = torch.tensor([[1,2],
                       [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0] #of 0 axis

tensor([1, 2])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

## Random Tensors
#### Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent tha data

 'Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers'

 Random Tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [19]:
# Create a random tensors of size(5,6,7)
random_tensor = torch.rand(5,6,7)
print(random_tensor.ndim)
print(random_tensor.shape)
random_tensor

3
torch.Size([5, 6, 7])


tensor([[[0.0047, 0.4154, 0.2533, 0.8090, 0.7020, 0.7400, 0.1709],
         [0.9379, 0.2433, 0.0803, 0.1974, 0.0517, 0.4039, 0.9563],
         [0.0570, 0.1999, 0.7151, 0.8075, 0.1154, 0.2018, 0.1232],
         [0.1319, 0.8477, 0.8170, 0.5999, 0.6178, 0.5813, 0.8096],
         [0.8319, 0.7568, 0.0209, 0.3090, 0.1277, 0.5599, 0.7376],
         [0.3182, 0.1233, 0.8744, 0.8639, 0.8357, 0.0477, 0.6163]],

        [[0.2812, 0.5848, 0.3362, 0.8977, 0.9605, 0.0576, 0.3365],
         [0.1913, 0.7497, 0.1268, 0.5935, 0.3630, 0.6795, 0.6364],
         [0.9070, 0.4386, 0.2068, 0.4618, 0.1739, 0.7092, 0.0328],
         [0.7859, 0.9577, 0.2615, 0.1027, 0.1969, 0.2416, 0.8234],
         [0.6152, 0.2185, 0.6880, 0.0356, 0.8375, 0.3166, 0.0150],
         [0.3026, 0.2455, 0.5757, 0.9230, 0.0969, 0.6808, 0.6796]],

        [[0.4368, 0.5933, 0.9788, 0.5424, 0.1222, 0.0658, 0.6669],
         [0.4629, 0.3204, 0.3984, 0.7388, 0.3112, 0.9510, 0.4223],
         [0.7699, 0.3569, 0.8336, 0.8462, 0.6826, 0.4909, 

In [20]:
#Create a random tensor with similar sahpe to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width in pixels, color channel(R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones

In [22]:
#Create a tensor of all zeros
zeros = torch.zeros(size=(4,5))
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [23]:
random_tensor2 = torch.rand(size=(4,5))
random_tensor2

tensor([[0.8068, 0.0259, 0.5605, 0.4018, 0.7019],
        [0.5412, 0.4500, 0.0512, 0.0991, 0.9874],
        [0.1422, 0.3411, 0.6220, 0.4288, 0.5063],
        [0.4290, 0.1487, 0.8142, 0.8824, 0.8261]])

In [24]:
zeros*random_tensor2

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [25]:
# create a tensor of all ones
ones = torch.ones(size=(4,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [28]:
# Use torch.arange()
one_to_ten = torch.arange(start=1,end=11,step=2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [29]:
#creating a tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

In [30]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1])

In [31]:
ten_random = torch.rand_like(input=one_to_ten,dtype=torch.float)
ten_random

tensor([0.9765, 0.8561, 0.6805, 0.1163, 0.1836])

### Tensor Data types
**Note:** Tensor data types is one of the 3 bog eroors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [33]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,4.0,5.0,6.0],dtype=None)
float_32_tensor

tensor([3., 4., 5., 6.])

In [34]:
float_32_tensor.dtype #default data type for tensor is float 32

torch.float32

In [35]:
float_16_tensor = torch.tensor([3.0, 4.0, 5.0],
                               dtype=torch.float16, #what data type is the tensor
                               device=None,  # What devide is your tensor on
                               requires_grad=False) #Whether or not to track gradient with this tensors operations
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [36]:
float_16_tensor.dtype

torch.float16

In [37]:
Float_16_tensor = float_32_tensor.type(torch.float16) #converting

In [38]:
Float_16_tensor.dtype,float_32_tensor.dtype

(torch.float16, torch.float32)

In [39]:
(Float_16_tensor*float_32_tensor).dtype

torch.float32

In [40]:
int_32_tensor = torch.tensor([3,4,5,6],dtype=torch.int32)
int_32_tensor

tensor([3, 4, 5, 6], dtype=torch.int32)

In [41]:
(int_32_tensor*float_32_tensor).dtype

torch.float32

In [42]:
int_32_tensor.device

device(type='cpu')

### Getting information from tensors
1. Tensor not right datatype - to do gey datatype from a tensor, can use tensor.dtype
2. Tensor not right shape- to get shape from a tensor, can use tensor.shape
3. Tensor not on the right device- to get device from a tensor, can use tensor.device

In [44]:
#creating tensor
some_tensor = torch.rand(4,5)
some_tensor

tensor([[0.2675, 0.7651, 0.7180, 0.0493, 0.2427],
        [0.7026, 0.8316, 0.1420, 0.0879, 0.9309],
        [0.9414, 0.4301, 0.1225, 0.8128, 0.2224],
        [0.9358, 0.2743, 0.0645, 0.8779, 0.6686]])

In [45]:
#Find information about tensor
print(some_tensor)
print(f"Datatype of a tensor: {some_tensor.dtype}")
print(f"Shape of a tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2675, 0.7651, 0.7180, 0.0493, 0.2427],
        [0.7026, 0.8316, 0.1420, 0.0879, 0.9309],
        [0.9414, 0.4301, 0.1225, 0.8128, 0.2224],
        [0.9358, 0.2743, 0.0645, 0.8779, 0.6686]])
Datatype of a tensor: torch.float32
Shape of a tensor: torch.Size([4, 5])
Device tensor is on: cpu


### Manipuating Tensor
  Tensor Operations include:
1) Addition
2) Subtraction
3) Multiplication
4) Division
5) Matrix Multiplication

In [47]:
# Creating Tensor
tensor = torch.tensor([1,2,3])
print(tensor + 10)
tensor

tensor([11, 12, 13])


tensor([1, 2, 3])

In [48]:
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [49]:
tensor - 10

tensor([ 0, 10, 20])

In [50]:
#From the pytorch in-built functions
print(torch.mul(tensor,10))
print(torch.add(tensor,10))
print(torch.sub(tensor,10))

tensor([100, 200, 300])
tensor([20, 30, 40])
tensor([ 0, 10, 20])


In [51]:
# Matrix Multiplication(dot product)
# Element wise multiplication
print(tensor,"*",tensor)
print(f"Equal to: {tensor*tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equal to: tensor([100, 400, 900])


In [52]:
# Matrix Multiplication
torch.matmul(tensor,tensor) # 10*10 + 20*20 + 30*30

tensor(1400)

In [53]:
10*10 + 20*20 + 30*30

1400

In [54]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i]*tensor[i]
print(value)

tensor(1400)
CPU times: user 857 μs, sys: 851 μs, total: 1.71 ms
Wall time: 1.7 ms


In [55]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 94 μs, sys: 12 μs, total: 106 μs
Wall time: 217 μs


tensor(1400)

In [56]:
### One of the most common error in deep learning is shape error
# 1) inner dimension must match
torch.matmul(torch.rand(3,2),torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [66]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.6312, 0.4684, 0.6210],
        [0.5320, 0.3496, 0.5194],
        [0.8787, 0.5652, 0.8568]])

In [68]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])

In [70]:
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [72]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [74]:
# to fix out tensor shape issues, we can manipulate the shape of one our tensor using transpose
tensor_B.T, tensor_B, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([2, 3]))

In [76]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

### Tensor aggregration
#### Finding the min, max, mean, sum, etc (tensor aggregration)

In [78]:
# Create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [80]:
# Finding the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [82]:
# Finding the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [84]:
# Finding the mean
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [86]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
# Note: torch.mean() function requires a tensor of float32 datatype to work

(tensor(45.), tensor(45.))

In [88]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [90]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [94]:
# Find the position in tensor that has the min value with argmin()
# It returns the index position of target tensor where the minmun value occurs
x.argmin()

(tensor(0), tensor(0))

In [96]:
x[0]

tensor(0)

In [98]:
# Find the position in tensor that has the maximum value
x.argmax()

tensor(9)

In [100]:
x[9]

tensor(90)

### Reshaping, stacking, squeezing and unsqueezing tensors
**.** Reshaping-reshapes an input tensor to a defined shape

**.** View-Return a view of an input tensor of certain shape but keep the same memory as the original tensor

**.** Stacking-combine multiple tensors on top of each other(vstack) pr side by side (hstack)

In [104]:
y = torch.arange(1., 10.)
y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [106]:
# Add an extra dimension
y_reshaped = y.reshape(1,9)
y_reshaped, y_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [108]:
# Change the view
z = y.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [112]:
# Changing the z changes y (because of a view of tensor share the same memory)
z[:,0]=10
z,y

(tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [120]:
# Stack tensors on the top of each other
y_stacked1 = torch.stack([y,y,y,y],dim=0)
y_stacked1

tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [122]:
y_stacked2 = torch.stack([y,y,y,y],dim=1)
y_stacked2

tensor([[10., 10., 10., 10.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.]])

In [129]:
# torch.squeeze() - removing the single dimensions from a target tensor
print(f"Previous tensor: {y_reshaped}")
print(f"Previous shape:{y_reshaped.shape}")

Previous tensor: tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])
Previous shape:torch.Size([1, 9])


In [131]:
y_squeezed = y_reshaped.squeeze()
print(f"\n New tensor:{y_squeezed}")
print(f"\n New shape: {y_squeezed.shape}")


 New tensor:tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

 New shape: torch.Size([9])


In [133]:
# torch.unsqueeze() - adds a single dimension to a target at specific dimension
print(f"Previous Tensor: {y_squeezed}")
print(f"Previoushape: {y_squeezed.shape}")

Previous Tensor: tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])
Previoushape: torch.Size([9])


In [143]:
y_unsqueezed = y_squeezed.unsqueeze(dim=0)
print(f"New tensor: {y_unsqueezed}")
print(f"New shape: {y_unsqueezed.shape}")

New tensor: tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])
New shape: torch.Size([1, 9])


In [145]:
# torch.permute - rearrange the dimensios of a target tensor in specified order
x_original = torch.rand(size=(224,224,3)) #[height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [147]:
x_original[0,0,0] = 1234
x_original[0,0,0], x_permuted[0,0,0]

(tensor(1234.), tensor(1234.))

### Indexing (selecting data from tensors)
It is similar to indexing with Numpy

In [156]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.reshape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 <function Tensor.reshape>)

In [158]:
#let's index on our new tensor(dim=0)
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [160]:
# let's index on middle bracket (dim=1)
x[0][1]

tensor([4, 5, 6])

In [166]:
# Indexing on the most inner bracket (last dimension)
x[0][1][2]

6

In [186]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [198]:
x[:,1,:]

tensor([[4, 5, 6]])

In [190]:
print(x[0,0,:])

tensor([1, 2, 3])


### Pytorch tensors and numpy
**.** Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)

**.** PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [209]:
# Converting NumPy array to tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
#When converting from numpy to pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [211]:
# Change the value of array, what will this do to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [213]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take random oyt of random)
To reduce the randomness in neural network and pytorch comes the concepts of **random seed.**

In [218]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1439, 0.8994, 0.9801, 0.6573],
        [0.3702, 0.7992, 0.3887, 0.3949],
        [0.4889, 0.5537, 0.3166, 0.3238]])
tensor([[0.4114, 0.8971, 0.9550, 0.5999],
        [0.9089, 0.9353, 0.6101, 0.2293],
        [0.2148, 0.2717, 0.5144, 0.4886]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [220]:
# Let's make some random but reproducible tensors
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [222]:
# Checking for GPU access with pytorch
torch.cuda.is_available()

False