### 1. Create a random tensor with shape(7,7)

In [3]:
import torch
import numpy as np

In [5]:
random_tensor = torch.rand(size=(7,7))
random_tensor

tensor([[0.4772, 0.0027, 0.0214, 0.0466, 0.0160, 0.0135, 0.6997],
        [0.2147, 0.7155, 0.2388, 0.1916, 0.3117, 0.8708, 0.1530],
        [0.9598, 0.2094, 0.8288, 0.7132, 0.8459, 0.4501, 0.6263],
        [0.0961, 0.7240, 0.2824, 0.6750, 0.1813, 0.5723, 0.2313],
        [0.4432, 0.2181, 0.0233, 0.8408, 0.1971, 0.8028, 0.0056],
        [0.4404, 0.7082, 0.2585, 0.4797, 0.6488, 0.8939, 0.5349],
        [0.7797, 0.9270, 0.8879, 0.1383, 0.1814, 0.5082, 0.3171]])

#### 2. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [9]:
random_tensor2 = torch.rand(1,7)
random_tensor2

tensor([[0.9054, 0.2498, 0.5859, 0.9034, 0.4422, 0.0247, 0.0855]])

In [11]:
torch.matmul(random_tensor, random_tensor2)  #it gives error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (7x7 and 1x7)

In [13]:
torch.matmul(random_tensor, random_tensor2.T)

tensor([[0.5545],
        [0.8586],
        [2.4900],
        [1.1573],
        [1.3365],
        [1.5152],
        [1.7026]])

#### Set the random seed to 0 and do exercises 2 & 3 over again.

In [18]:
RANDOM_SEED = 0
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_A = torch.rand(size=(7,7))

torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_B = torch.rand(size=(1,7))
print(random_tensor_A)
print(random_tensor_B)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])


In [20]:
torch.matmul(random_tensor_A, random_tensor_B.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

#### Create two random tensors of shape (2, 3), perform a matrix multiplication on the tensors

In [23]:
torch.manual_seed(1234)
random_tensor_C = torch.rand(size=(2,3))

torch.random.manual_seed(1234)
random_tensor_D = torch.rand(size=(2,3))

In [25]:
final_tensor_A = torch.matmul(random_tensor_C, random_tensor_D.T)
final_tensor_A

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]])

#### Find the maximum and minimum values of the above output.

In [37]:
print(f"Maximun: {final_tensor_A.max()}")
print(f"Minimum: {final_tensor_A.min()}")

Maximun: 0.6287278532981873
Minimum: 0.21611443161964417


In [53]:
print(f"Note: PyTorch flattens the tensor into a 1D array before finding the index of the maximum value.")
print(f"Index of maximum value: {final_tensor_A.argmax()}")
print(f"Index of minimum value: {final_tensor_A.argmin()}")

Note: PyTorch flattens the tensor into a 1D array before finding the index of the maximum value.
Index of maximum value: 3
Index of minimum value: 1


#### Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [62]:
torch.manual_seed(7)
random_tensor_E = torch.rand(size=(1,1,1,10))
print(f"Previous Tensor: {random_tensor_E}")
print(f"Previous Shape: {random_tensor_E.shape}")

Previous Tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Previous Shape: torch.Size([1, 1, 1, 10])


In [64]:
random_tensor_E_squeezed = random_tensor_E.squeeze()
print(f"New tensor: {random_tensor_E_squeezed}")
print(f"New Shape: {random_tensor_E_squeezed.shape}")

New tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
New Shape: torch.Size([10])
