In [1]:
import torch

In [3]:
torch.__version__

'2.4.1'

In [9]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [11]:
scalar.ndim

0

In [13]:
scalar.shape

torch.Size([])

In [17]:
vector = torch.tensor([7])
vector, vector.ndim, vector.shape

(tensor([7]), 1, torch.Size([1]))

In [21]:
matrix = torch.tensor([[1,2],[3,4]])
matrix, matrix.ndim, matrix.shape

(tensor([[1, 2],
         [3, 4]]),
 2,
 torch.Size([2, 2]))

In [27]:
random_tensor = torch.rand(size=[3,4])
random_tensor

tensor([[0.2417, 0.9425, 0.2736, 0.6677],
        [0.8700, 0.6700, 0.8717, 0.5402],
        [0.9274, 0.6049, 0.9383, 0.3502]])

In [43]:
zeros_tensor = torch.zeros(size=[3,2])
zeros_tensor, zeros_tensor.dtype

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.]]),
 torch.float32)

In [33]:
ones_tensor = torch.ones(size=[2,3])
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [39]:
tensor2 = random_tensor.ones_like(ones_tensor)
tensor2

AttributeError: 'Tensor' object has no attribute 'ones_like'

In [41]:
tensor3 = torch.arange(start=0, end=101, step = 3)
tensor3

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
        54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [47]:
tensor3 = torch.tensor([1,2,3],
                      dtype=torch.float16)
tensor3

tensor([1., 2., 3.], dtype=torch.float16)

In [49]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [51]:
model.to(device)

NameError: name 'model' is not defined

In [55]:
tensor4 = torch.tensor([1,2,3])
print(tensor4 + 10)
print(tensor4 - 10)
print(tensor4 * 10)
print(tensor4 * 10)
print(tensor4@tensor4)
print(torch.matmul(tensor4, tensor4))

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([10, 20, 30])
tensor(14)
tensor(14)


In [61]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]],dtype=torch.float32)
tensor_B = torch.tensor([[7,8],
                        [9,10],
                        [11,12]],dtype=torch.float32)
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23.,  29.,  35.],
        [ 53.,  67.,  81.],
        [ 83., 105., 127.]])

In [1]:
print("Hello World")

Hello World


In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
import matplotlib.pyplot as plt

In [5]:
import seaborn as sns

In [6]:
import torch

In [7]:
torch.__version__

'2.4.1'